path_data = '../'
annotations_path = path_data + 'data/annotations/'
questions_path = path_data + 'data/questions/'
images_path = path_data + 'data/images/'
device = 'Ascend'
alter_ans_num = 10
pretrained = False
pretrained_model_path = ''
epochs = 5
batch_size = 4
initial_lr = 2e-3
